[build]
  command = "npm run build"
  publish = "dist/client"
  functions = ".netlify/v1/functions"

[[redirects]]
  from = "/og-share.jpg"
  to = "/share.jpg"
  status = 301
  force = true

[build.environment]
  NODE_VERSION = "20"

[dev]
  command = "npm run dev"
  port = 5173
