// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShareDotjpgRouteImport } from './routes/share[.]jpg'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as DenunciasRouteImport } from './routes/denuncias'
import { Route as CampanhasRouteImport } from './routes/campanhas'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdsDottxtRouteImport } from './routes/ads[.]txt'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampanhaSlugRouteImport } from './routes/campanha.$slug'
import { Route as AdminEntrarRouteImport } from './routes/admin.entrar'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedNovaCampanhaRouteImport } from './routes/_authenticated/nova-campanha'
import { Route as AuthenticatedAceitarTermosRouteImport } from './routes/_authenticated/aceitar-termos'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedEditarIdRouteImport } from './routes/_authenticated/editar.$id'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated/admin/logs'
import { Route as AuthenticatedAdminDenunciasRouteImport } from './routes/_authenticated/admin/denuncias'
import { Route as AuthenticatedAdminConteudoRouteImport } from './routes/_authenticated/admin/conteudo'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin/configuracoes'
import { Route as AuthenticatedAdminCampanhasRouteImport } from './routes/_authenticated/admin/campanhas'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin/analytics'

const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareDotjpgRoute = ShareDotjpgRouteImport.update({
  id: '/share.jpg',
  path: '/share.jpg',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const DenunciasRoute = DenunciasRouteImport.update({
  id: '/denuncias',
  path: '/denuncias',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanhasRoute = CampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsDottxtRoute = AdsDottxtRouteImport.update({
  id: '/ads.txt',
  path: '/ads.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanhaSlugRoute = CampanhaSlugRouteImport.update({
  id: '/campanha/$slug',
  path: '/campanha/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEntrarRoute = AdminEntrarRouteImport.update({
  id: '/admin/entrar',
  path: '/admin/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNovaCampanhaRoute =
  AuthenticatedNovaCampanhaRouteImport.update({
    id: '/nova-campanha',
    path: '/nova-campanha',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAceitarTermosRoute =
  AuthenticatedAceitarTermosRouteImport.update({
    id: '/aceitar-termos',
    path: '/aceitar-termos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedEditarIdRoute = AuthenticatedEditarIdRouteImport.update({
  id: '/editar/$id',
  path: '/editar/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminDenunciasRoute =
  AuthenticatedAdminDenunciasRouteImport.update({
    id: '/denuncias',
    path: '/denuncias',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminConteudoRoute =
  AuthenticatedAdminConteudoRouteImport.update({
    id: '/conteudo',
    path: '/conteudo',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCampanhasRoute =
  AuthenticatedAdminCampanhasRouteImport.update({
    id: '/campanhas',
    path: '/campanhas',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ads.txt': typeof AdsDottxtRoute
  '/auth': typeof AuthRoute
  '/campanhas': typeof CampanhasRoute
  '/denuncias': typeof DenunciasRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/share.jpg': typeof ShareDotjpgRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/aceitar-termos': typeof AuthenticatedAceitarTermosRoute
  '/nova-campanha': typeof AuthenticatedNovaCampanhaRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/admin/entrar': typeof AdminEntrarRoute
  '/campanha/$slug': typeof CampanhaSlugRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/campanhas': typeof AuthenticatedAdminCampanhasRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/conteudo': typeof AuthenticatedAdminConteudoRoute
  '/admin/denuncias': typeof AuthenticatedAdminDenunciasRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/editar/$id': typeof AuthenticatedEditarIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ads.txt': typeof AdsDottxtRoute
  '/auth': typeof AuthRoute
  '/campanhas': typeof CampanhasRoute
  '/denuncias': typeof DenunciasRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/share.jpg': typeof ShareDotjpgRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/aceitar-termos': typeof AuthenticatedAceitarTermosRoute
  '/nova-campanha': typeof AuthenticatedNovaCampanhaRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/admin/entrar': typeof AdminEntrarRoute
  '/campanha/$slug': typeof CampanhaSlugRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/campanhas': typeof AuthenticatedAdminCampanhasRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/conteudo': typeof AuthenticatedAdminConteudoRoute
  '/admin/denuncias': typeof AuthenticatedAdminDenunciasRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/editar/$id': typeof AuthenticatedEditarIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/ads.txt': typeof AdsDottxtRoute
  '/auth': typeof AuthRoute
  '/campanhas': typeof CampanhasRoute
  '/denuncias': typeof DenunciasRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/share.jpg': typeof ShareDotjpgRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/aceitar-termos': typeof AuthenticatedAceitarTermosRoute
  '/_authenticated/nova-campanha': typeof AuthenticatedNovaCampanhaRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/admin/entrar': typeof AdminEntrarRoute
  '/campanha/$slug': typeof CampanhaSlugRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/campanhas': typeof AuthenticatedAdminCampanhasRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/conteudo': typeof AuthenticatedAdminConteudoRoute
  '/_authenticated/admin/denuncias': typeof AuthenticatedAdminDenunciasRoute
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/editar/$id': typeof AuthenticatedEditarIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ads.txt'
    | '/auth'
    | '/campanhas'
    | '/denuncias'
    | '/politica-de-privacidade'
    | '/share.jpg'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos-de-uso'
    | '/admin'
    | '/aceitar-termos'
    | '/nova-campanha'
    | '/painel'
    | '/admin/entrar'
    | '/campanha/$slug'
    | '/admin/analytics'
    | '/admin/campanhas'
    | '/admin/configuracoes'
    | '/admin/conteudo'
    | '/admin/denuncias'
    | '/admin/logs'
    | '/admin/usuarios'
    | '/editar/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ads.txt'
    | '/auth'
    | '/campanhas'
    | '/denuncias'
    | '/politica-de-privacidade'
    | '/share.jpg'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos-de-uso'
    | '/aceitar-termos'
    | '/nova-campanha'
    | '/painel'
    | '/admin/entrar'
    | '/campanha/$slug'
    | '/admin/analytics'
    | '/admin/campanhas'
    | '/admin/configuracoes'
    | '/admin/conteudo'
    | '/admin/denuncias'
    | '/admin/logs'
    | '/admin/usuarios'
    | '/editar/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ads.txt'
    | '/auth'
    | '/campanhas'
    | '/denuncias'
    | '/politica-de-privacidade'
    | '/share.jpg'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos-de-uso'
    | '/_authenticated/admin'
    | '/_authenticated/aceitar-termos'
    | '/_authenticated/nova-campanha'
    | '/_authenticated/painel'
    | '/admin/entrar'
    | '/campanha/$slug'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/campanhas'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/conteudo'
    | '/_authenticated/admin/denuncias'
    | '/_authenticated/admin/logs'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/editar/$id'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdsDottxtRoute: typeof AdsDottxtRoute
  AuthRoute: typeof AuthRoute
  CampanhasRoute: typeof CampanhasRoute
  DenunciasRoute: typeof DenunciasRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  ShareDotjpgRoute: typeof ShareDotjpgRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  AdminEntrarRoute: typeof AdminEntrarRoute
  CampanhaSlugRoute: typeof CampanhaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share.jpg': {
      id: '/share.jpg'
      path: '/share.jpg'
      fullPath: '/share.jpg'
      preLoaderRoute: typeof ShareDotjpgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denuncias': {
      id: '/denuncias'
      path: '/denuncias'
      fullPath: '/denuncias'
      preLoaderRoute: typeof DenunciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanhas': {
      id: '/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof CampanhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads.txt': {
      id: '/ads.txt'
      path: '/ads.txt'
      fullPath: '/ads.txt'
      preLoaderRoute: typeof AdsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanha/$slug': {
      id: '/campanha/$slug'
      path: '/campanha/$slug'
      fullPath: '/campanha/$slug'
      preLoaderRoute: typeof CampanhaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/entrar': {
      id: '/admin/entrar'
      path: '/admin/entrar'
      fullPath: '/admin/entrar'
      preLoaderRoute: typeof AdminEntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nova-campanha': {
      id: '/_authenticated/nova-campanha'
      path: '/nova-campanha'
      fullPath: '/nova-campanha'
      preLoaderRoute: typeof AuthenticatedNovaCampanhaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/aceitar-termos': {
      id: '/_authenticated/aceitar-termos'
      path: '/aceitar-termos'
      fullPath: '/aceitar-termos'
      preLoaderRoute: typeof AuthenticatedAceitarTermosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/editar/$id': {
      id: '/_authenticated/editar/$id'
      path: '/editar/$id'
      fullPath: '/editar/$id'
      preLoaderRoute: typeof AuthenticatedEditarIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/denuncias': {
      id: '/_authenticated/admin/denuncias'
      path: '/denuncias'
      fullPath: '/admin/denuncias'
      preLoaderRoute: typeof AuthenticatedAdminDenunciasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/conteudo': {
      id: '/_authenticated/admin/conteudo'
      path: '/conteudo'
      fullPath: '/admin/conteudo'
      preLoaderRoute: typeof AuthenticatedAdminConteudoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/campanhas': {
      id: '/_authenticated/admin/campanhas'
      path: '/campanhas'
      fullPath: '/admin/campanhas'
      preLoaderRoute: typeof AuthenticatedAdminCampanhasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminCampanhasRoute: typeof AuthenticatedAdminCampanhasRoute
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminConteudoRoute: typeof AuthenticatedAdminConteudoRoute
  AuthenticatedAdminDenunciasRoute: typeof AuthenticatedAdminDenunciasRoute
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
    AuthenticatedAdminCampanhasRoute: AuthenticatedAdminCampanhasRoute,
    AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
    AuthenticatedAdminConteudoRoute: AuthenticatedAdminConteudoRoute,
    AuthenticatedAdminDenunciasRoute: AuthenticatedAdminDenunciasRoute,
    AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
    AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAceitarTermosRoute: typeof AuthenticatedAceitarTermosRoute
  AuthenticatedNovaCampanhaRoute: typeof AuthenticatedNovaCampanhaRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedEditarIdRoute: typeof AuthenticatedEditarIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAceitarTermosRoute: AuthenticatedAceitarTermosRoute,
  AuthenticatedNovaCampanhaRoute: AuthenticatedNovaCampanhaRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedEditarIdRoute: AuthenticatedEditarIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdsDottxtRoute: AdsDottxtRoute,
  AuthRoute: AuthRoute,
  CampanhasRoute: CampanhasRoute,
  DenunciasRoute: DenunciasRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  ShareDotjpgRoute: ShareDotjpgRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  AdminEntrarRoute: AdminEntrarRoute,
  CampanhaSlugRoute: CampanhaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
